apiVersion: v1
kind: ConfigMap
metadata:
  name: assets-config
data:
  PORT: "3002"
  DB_HOST: "dpg-d8ke6af7f7vs73dmug90-a.oregon-postgres.render.com"
  DB_PORT: "5432"
  DB_NAME: "Assets"
  DB_USER: "banksystem"
  DB_SSL: "true"