apiVersion: apps/v1
kind: Deployment
metadata:
  name: assets
spec:
  replicas: 1
  selector:
    matchLabels:
      app: assets
  template:
    metadata:
      labels:
        app: assets
    spec:
      containers:
        - name: assets
          image: assets:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 3002
          envFrom:
            - configMapRef:
                name: assets-config
          env:
            - name: DB_PASSWORD
              value: "74zk0Sj4QlDkBbnhA8bJrM3L2zp5K5CA"